# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
# LTS, current stable, and nightly
  - 1.0.5
  - 1.5.3
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
      
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FaSTLMM"); Pkg.test("FaSTLMM"; coverage=true)'